name: EFC

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4"

jobs:
  EFC:
    name: Claim Freebie
    runs-on: ubuntu-latest
    steps:
      - name: Setup data folder
        env:
          EG_AUTH_JSON: ${{ secrets.EG_DEVICE_AUTH }}
        run: |
          mkdir "$GITHUB_WORKSPACE/data"
          echo "$EG_AUTH_JSON" > $GITHUB_WORKSPACE/data/device_auths.json
          wget https://raw.githubusercontent.com/Revadike/epicgames-freebies-claimer/master/data/config.example.json \
            -O "$GITHUB_WORKSPACE/data/config.json"

      - name: Setup config file
        env:
          EG_CONFIG_JSON: ${{ secrets.EG_CONFIG_JSON }}
        if: ${{ env.EG_CONFIG_JSON != null }}
        run: echo "$EG_CONFIG_JSON" > $GITHUB_WORKSPACE/data/config.json

      - name: Claim
        run: |
          docker run --rm --pull always \
            --volume "$GITHUB_WORKSPACE/data:/app/data" \
            ghcr.io/jackblk/epicgames-freebies-claimer:latest
